package com.example.bulosfrontend.ui.theme

import androidx.compose.ui.graphics.Color

val AppBackground = Color(0xFFF4EEE3)
val PrimaryGreen = Color(0xFF2E5D2E)
val SpeechCardGreen = Color(0xFF245326)
val WarmWhiteCard = Color(0xFFFFFDF8)
val TextTranslationCard = Color(0xFFF4E4C9)
val DictionaryCard = Color(0xFFECDCBF)
val HistoryCard = Color(0xFFDEEACC)
val MainText = Color(0xFF2C1810)
val MutedText = Color(0xFF7A6650)
val GoldenAccent = Color(0xFFC17A3C)
val PatternGreen = Color(0xFF163F20)
val DarkStatusGreen = Color(0xFF1A3D1A)

val ForestGreen = PrimaryGreen
val DeepForestGreen = DarkStatusGreen
val SoftGreen = Color(0xFFDCEACB)
val Cream = Color(0xFFF8F1E5)
val WarmWhite = Color(0xFFFFFCF7)
val NavigationCream = Color(0xFFFFFDF9)
val Sand = Color(0xFFF0DFC0)
val Peach = Color(0xFFF5E2D3)
val MistBlue = Color(0xFFDCE6F1)
val Olive = Color(0xFF7F6D3E)
val WarmBrown = Color(0xFF705634)
val SplashSage = Color(0xFF769274)
val SplashGold = Color(0xFFE7B861)
val SplashDeepGreen = Color(0xFF173819)
val HomeSpeechGreen = Color(0xFF3B6A3C)
val HomeTextSand = Color(0xFFF2DFC0)
val HomeDictionarySand = Color(0xFFEEDDB9)
val HomeHistorySage = Color(0xFFDCEACB)
val HomeSettingsBlue = Color(0xFFDDE6F0)
val HomeSettingsInk = Color(0xFF234D78)
val HomeCardBorder = Color(0xFFE5DAC8)
val HomeTextTranslationCard = Color(0xFFA88F76)
val HomeSavedHistoryCard = Color(0xFFC4B197)
val HomeSettingsCard = Color(0xFFD8CAB5)
val HomeHelpCard = Color(0xFFE8DED2)
val HomeRecentTranslationCard = Color(0xFFFFF3DA)
val RecordingRed = Color(0xFFFF3045)
val InnerVoiceRing = Color(0xFFFF6070)
val OuterVoiceRing = Color(0xFFFFA0A8)
val StrongInnerRed = Color(0xFFFF3F55)
val StrongMiddlePink = Color(0xFFFF6578)
val StrongOuterPink = Color(0xFFFF8998)
val QuietVoiceInner = Color(0xFFFF8F9C)
val QuietVoiceMiddle = Color(0xFFFFAAB4)
val QuietVoiceOuter = Color(0xFFFFC2C9)
val LoudVoiceInner = Color(0xFFFF3045)
val LoudVoiceMiddle = Color(0xFFFF5368)
val LoudVoiceOuter = Color(0xFFFF8292)
val VoiceReviewOrange = Color(0xFFC77932)
val ResultSage = Color(0xFFE6EFD9)

val DarkHomeHeader = Color(0xFF0E2A1C)
val DarkHomeHeaderMid = Color(0xFF143D27)
val DarkHomeBody = Color(0xFF17140F)
val DarkEarthSurface = Color(0xFF201C17)
val DarkWarmText = Color(0xFFF2EFE7)
val DarkMutedText = Color(0xFFB9B1A3)
val DarkWarmOutline = Color(0xFF3B342C)
